Upload_Sample/Controllers/FullUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Upload_Sample.Models;
using Upload_Sample.Models.Entities;
using Upload_Sample.Models.ViewModels;

namespace Upload_Sample.Controllers
{
    public class FullUploadController : Controller
    {
        private readonly ProjectDbContext _context;

        public FullUploadController(ProjectDbContext context)
        {
            _context = context;
        }

        public IActionResult PodcastList()
        {
            var list = _context.Podcasts.ToList();
            return View(list);
        }

        public IActionResult CreatePodcast()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePodcast(PodcastViewModel Podcasts, IFormFile file, IFormFile image)
        { 
            // Upload Image
            var pathImage = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/podcasts", image.FileName);
            using (var stream = new FileStream(pathImage, FileMode.Create))
            {
                image.CopyTo(stream);
            }

            var model = _context.Podcasts.Add(new Podcast
            {
                ArtistName = Podcasts.Podcasts.ArtistName,
                PodcastName = Podcasts.Podcasts.PodcastName,
                Image = "/images/podcasts/" + image.FileName,
                CreateDate = DateTime.Now,
            });

            _context.SaveChanges();

            foreach (var item in Podcasts.PodcastFile)
            {
                // Upload File Podcast
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/files/podcasts", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                _context.PodcastFiles.Add(new PodcastFile
                {
                    Name = item.Name,
                    File = "/files/podcasts/" + file.FileName,
                    PodcastId = model.Entity.Id
                });
            }
            _context.SaveChanges();

            //foreach (var item in podcast)
            //{
            //    // Upload File Podcast
            //    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/files/podcasts", item.Files.FileName);
            //    using (var stream = new FileStream(path, FileMode.Create))
            //    {
            //        item.Files.CopyTo(stream);
            //    }

            //    // Upload Image
            //    var pathImage = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/podcasts", item.Image.FileName);
            //    using (var stream = new FileStream(path, FileMode.Create))
            //    {
            //        item.Files.CopyTo(stream);
            //    }

            //    _context.Podcasts.Add(new Podcast
            //    {
            //        ArtistName = item.Podcasts.ArtistName,
            //        PodcastName = item.Podcasts.PodcastName,
            //        Image = "/images/podcasts/" + item.Image.FileName,
            //        CreateDate = DateTime.Now,
            //    });
            //}

            //_context.SaveChanges();

            return RedirectToAction("PodcastList");
        }
    }
}

Upload_Sample/Views/FullUpload/CreatePodcast.cshtml
@model Upload_Sample.Models.ViewModels.PodcastViewModel

@{
    ViewData["Title"] = "CreatePodcast";
}

<div class="container">
    <!-- Basic form layout section start -->
    <section id="horizontal-form-layouts">
        <div class="row">
            <div class="col-xl-6 offset-3 col-lg-12">
                <div class="card mt-4">
                    <div class="card-content collpase show">
                        <div class="card-header">
                            <h2>Add Podcast</h2>
                        </div>
                        <div class="card-body">
                            <form asp-action="CreatePodcast" asp-controller="FullUpload" enctype="multipart/form-data" class="form form-horizontal">
                                <div class="form-body" id="list">

                                    <div class="form-group row">
                                        <label class="col-md-3 label-control" for="projectinput5">Artist Name</label>
                                        <div class="col-md-9">
                                            <input type="text" asp-for="Podcasts.ArtistName" id="projectinput5" class="form-control" placeholder="Artist Name">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-md-3 label-control" for="projectinput5">Podcast Name</label>
                                        <div class="col-md-9">
                                            <input type="text" asp-for="Podcasts.PodcastName" id="projectinput5" class="form-control" placeholder="Podcast Name">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-md-3 label-control">Image</label>
                                        <div class="col-md-9">
                                            <label id="projectinput8" class="file center-block">
                                                <input type="file" name="image" id="file">
                                                <span class="file-custom"></span>
                                            </label>
                                        </div>
                                    </div>

                                    <hr />

                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label class="col-md-9 label-control" for="projectinput5">Track Name</label>
                                            <div class="col-md-12">
                                                <input type="text" name="podcast[0].TrackName" id="projectinput5" class="form-control" placeholder="Track Name">
                                            </div>
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label class="col-md-6 label-control">Music File</label>
                                            <div class="col-md-6">
                                                <label id="projectinput8" class="file center-block">
                                                    <input type="file" name="file[0]" id="file">
                                                    <span class="file-custom"></span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="btn btn-success mb-4" id="addMore">Add</div>

                                <div class="form-actions right">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="la la-check-square-o"></i> Create
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!-- // Basic form layout section end -->
</div>

@section script
{
    <script>
        var index = 1;
        $("#addMore").click(function () {
            var form1 = "<div class='form-row'><div class='form-group col-md-6'><label class='col-md-9 label-control' for='projectinput5'>Track Name</label><div class='col-md-12'><input type='text' asp-for='TrackName' id='projectinput5' class='form-control' placeholder='Track Name'></div></div>";
            var form2 = "<div class='form-group col-md-6'><label class='col-md-6 label-control'>Music File</label><div class='col-md-6'><label id='projectinput8' class='file center-block'><input type='file' name='music' id='file'><span class='file-custom'></span></label></div></div></div>";
            //var form3 = "<div class='form-group row'><label class='col-md-3 label-control'>Image</label><div class='col-md-9'><label id='projectinput8' class='file center-block'><input type='file' name='file[" + index + "]' id='file'><span class='file-custom'></span></label></div></div>";
            $("#list").append(form1 + form2);
            index++;
        });
    </script>
}

Upload_Sample/Views/FullUpload/PodcastList.cshtml
@model IEnumerable<Upload_Sample.Models.Entities.Podcast>

@{
    ViewData["Title"] = "PodcastList";
}

@{
    var i = 1;
}

<div class="container">
    <div class="card mt-4">
        <div class="card-header">
            <a href="/FullUpload/CreatePodcast" class="btn btn-primary col-md-2">New Podcast</a>
        </div>
    </div>
    <div class="card-content collapse show " style="background-color:#fff;">
        <div class="table-responsive">
            <table class="table table-hover mb-0">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Image</th>
                        <th>Artist Name</th>
                        <th>Podcast Name</th>
                        <th>Created Date</th>
                        <th>Info</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var podcast in Model)
                    {
                    <tr>
                        <th scope="row">@i</th>
                        <td><img src="~/images/@podcast.Image" alt="@podcast.PodcastName" style="border-radius:50%;" height="30" width="30" /></td>
                        <td>@podcast.ArtistName</td>
                        <td>@podcast.PodcastName</td>
                        <td>@podcast.CreateDate</td>
                        <td>
                            <a href="/FullUpload/EditPodcast/@podcast.Id" class="btn btn-sm btn-outline-primary">Edit</a>
                            <a href="/FullUpload/DeletePodcast/@podcast.Id" class="btn btn-sm btn-outline-danger">Delete</a>
                        </td>
                    </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>